name: Scrape IMDb Top 250

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs daily at 17:40 UTC (11:10 PM IST)
  # For testing, uncomment the following line to trigger on pushes:
  # push:

jobs:
  scrape-imdb:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your preferred version

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv venv && uv pip install httpx lxml cssselect

      - name: Run scraper
        working-directory: .
        run: python script.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.json
          git commit -m "Update IMDb Top 250 data [skip ci]" || exit 0
          git push origin main -f --token ${{ secrets.GITHUB_TOKEN }}
          
      - name: List installed packages (for debugging)
        if: always() # Always run this step, even if previous steps fail
        run: uv venv && uv pip list
